name: Test

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4.0.0
        with:
          version: latest

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1

      - name: Install dependencies
        run: pnpm i && pnpm cypress install

      - name: Validate
        run: pnpm run-p lint test:ci test:e2e:ci
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Upload coverage
        uses: codecov/codecov-action@v4
